In [1]:
import numpy as np
import SimpleITK as sitk

In [2]:
label1 = './best_results/baseline/scan_24_label_1.nii.gz'
label2 = './best_results/baseline/scan_24_label_2.nii.gz'
label3 = './best_results/baseline/scan_24_label_3.nii.gz'
label6 = './best_results/baseline/scan_24_label_6.nii.gz'

im_obj1 = sitk.ReadImage(label1)
im_obj2 = sitk.ReadImage(label2)
im_obj3 = sitk.ReadImage(label3)
im_obj6 = sitk.ReadImage(label6)

a1 = sitk.GetArrayFromImage(im_obj1)
a2 = sitk.GetArrayFromImage(im_obj2)
a3 = sitk.GetArrayFromImage(im_obj3)
a6 = sitk.GetArrayFromImage(im_obj6)

In [3]:
np.unique(a1), np.unique(a2), np.unique(a3), np.unique(a6)

(array([0., 1.]), array([0., 2.]), array([0., 3.]), array([0., 6.]))

In [4]:
all_in_one = a1
all_in_one[a2 == 2] = 2
all_in_one[a3 == 3] = 3
all_in_one[a6 == 6] = 6

np.unique(all_in_one)

array([0., 1., 2., 3., 6.])

In [7]:
a = all_in_one.astype(np.uint8)
new_img = sitk.GetImageFromArray(a)
new_img = copy_info(im_obj1, new_img)
sitk.WriteImage(new_img, './best_results/baseline/label_24_uint8.nii.gz')

In [5]:
sitk.GetArrayFromImage(im_obj)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [6]:
# copy spacing and orientation info between sitk objects
def copy_info(src, dst):
    dst.SetSpacing(src.GetSpacing())
    dst.SetOrigin(src.GetOrigin())
    dst.SetDirection(src.GetDirection())
    # dst.CopyInfomation(src)
    return dst

In [17]:
import numpy as np

a_img = sitk.ReadImage('./best_results/label_24.nii.gz')
a = sitk.GetArrayFromImage(a_img)
a = a.astype(np.uint8)

In [18]:
new_img = sitk.GetImageFromArray(a)
new_img = copy_info(a_img, new_img)
sitk.WriteImage(new_img, './best_results/label_24_uint8.nii.gz')

In [19]:
a_img = sitk.ReadImage('./best_results/label_24_uint8.nii.gz')
a = sitk.GetArrayFromImage(a_img)

In [23]:
np.unique(a)

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=uint8)